logging:
  level:
    org:
      springframework: trace
    com:
      github:
        peacetrue: trace
peacetrue:
  log:
    pointcut-infos:
      LogServiceImpl_query:
        module-code: log
        #        record-id: '#p0.id'
        operate-code: query
        description: 分页查询日志
        creator-id: 1
spring:
  profiles:
    include: datasource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
#    default-property-inclusion: non_empty

server:
  port: 8081


